services:
  db:
    image: postgres:16.4-bookworm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123Mudar
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge